强大的科学计算模块，值得好好学习与应用：最好能实践

In [1]:
import numpy as np

数组是numpy中的核心类型，整个模块都是以这个为基础的

# 一、基本介绍

In [5]:
a = np.array([1, 2, 3, 4])
type(a)  #类型是numpy中的n维数组

numpy.ndarray

In [18]:
np.array([[1, 2, 3],
         [4, 5, 6]])  #生成多维数组

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
#与列表不同的是，列表没法简单的每个元素加一，或者两个列表对应元素相加,或者乘法操作都是对应元素操作
a + 1

array([2, 3, 4, 5])

In [10]:
b = np.array([-1, -2, -3, -4])
a + b

array([0, 0, 0, 0])

In [11]:
a * a

array([ 1,  4,  9, 16])

In [12]:
c = [1, 2, 3, 4]
d = [-1, -2, -3, -4]
c + 1  #会报错，因为类型不同不能相加

TypeError: can only concatenate list (not "int") to list

In [13]:
c + d  #列表的加法只是列表的合并而已

[1, 2, 3, 4, -1, -2, -3, -4]

# 二、数组的属性

In [19]:
print(a.shape)
np.shape(a)  #两种方法均可以查看数组的形状，不过np.shape可以将非数组的类型先转化为数组，再显示其形状

(4,)


(4,)

与列表不同的是，数组的元素要求类型必须完全一样

In [22]:
print(a.dtype)  #数组中的数据的类型
print(a.itemsize)  #每个元素所占字节数
print(a.size)  #数组中元素的总数

int32
4
4


In [23]:
a.nbytes  #这个数组所占内存的大小=itemsize*size

16

In [24]:
a.ndim  #数组的维度

1

数组中的元素类型在创建之后就不能修改，如果传入的类型不同的话，py会在可以转化的情况下自动转化为同一类型

In [32]:
e = np.array([1 + 2j, 3, 4.2])  #初始化数据类型不同时，py会自动统一为一种类型
e.dtype

dtype('complex128')

In [40]:
e.imag

array([2., 0., 0.])

In [34]:
e.real  #实部和虚部调取并可以修改

array([1. , 3. , 4.2])

In [43]:
##若有字符串和数字类型的混合，numpy会把他们都转化为字符串
f = np.array(["abc", 1, 2.0])
f  #类型很奇怪，看不懂，但元素确实都转换成了字符串
#u3表示unicode字符串，最长为3

array(['abc', '1', '2.0'], dtype='<U3')

In [49]:
g = np.array([[1, 2, 3], (1, 2, 3), 4])
g  #在有更多类型的时候，会直接存储为object类型

array([list([1, 2, 3]), (1, 2, 3), 4], dtype=object)

In [50]:
g * 2

array([list([1, 2, 3, 1, 2, 3]), (1, 2, 3, 1, 2, 3), 8], dtype=object)

## 1.数组类型的转换

In [34]:
a = [1, 2, 3]
np.asarray(a)

array([1, 2, 3])

In [35]:
np.asarray([-255, 5, 6], dtype="uint8")

array([1, 5, 6], dtype=uint8)

In [36]:
np.asarray(a) is a

False

In [40]:
np.array(a) is a  #两种数组生成方法均复制一个新的数组

False

In [42]:
b = np.array([1, 2, 3])
b.astype(float)

array([1., 2., 3.])

In [45]:
np.array([1.0, -1.0, 0.0]) / 0.0  #数组中可以有inf无穷大出现，不会抛出异常；同时当不是确定数的时候，就会存储为nan（not a number）

D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ inf, -inf,  nan])

view函数

In [36]:
a = np.array([1, 2, 3, 4], dtype="int32")
a

array([1, 2, 3, 4])

In [37]:
a.view("complex64")  #view函数，用不同的数据类型解释原来的数组内存，会得出不同的结果

array([1.e-45+3.e-45j, 4.e-45+6.e-45j], dtype=complex64)

## 2.数组的生成

In [2]:
np.zeros((2,3,4), dtype=int)  #生成0矩阵

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [3]:
np.ones((2,3,4), dtype=int)  #生成1矩阵

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

arange函数

In [5]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

由于浮点数可能存在精度问题，所以有时候生成的数组，会包括结束参数（上面来说就是10）

linspace函数

In [7]:
np.linspace(0, 1, 5, endpoint=False)  #一定程度可以消除浮点数精度的问题

array([0. , 0.2, 0.4, 0.6, 0.8])

empty函数

In [17]:
np.empty((2, 3, 4), dtype=int)  #生成指定形状的元素随机的数组，只是开辟了内存

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

## 3.数组的索引

In [21]:
a = np.array([0, 1, 2, 3])
a[::-1]

array([3, 2, 1, 0])

In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
a[-1, -1]  #快速找到多维数组最后一个元素

8

In [26]:
a[0:2, 2:4]

array([[3, 4],
       [7, 8]])

## 4.数组的迭代

一维情况下和列表相同

In [6]:
a = np.arange(5)
for i in a:
    print(i)


0
1
2
3
4


多维情况下的迭代：只会对数组的第一维度进行迭代

In [9]:
b = np.arange(24)
b.shape = (4, 6)
for i in b:
    print(i, type(i))
#按照行进行迭代输出

[0 1 2 3 4 5] <class 'numpy.ndarray'>
[ 6  7  8  9 10 11] <class 'numpy.ndarray'>
[12 13 14 15 16 17] <class 'numpy.ndarray'>
[18 19 20 21 22 23] <class 'numpy.ndarray'>


可以使用ndenumerate函数迭代多维数组中的每个元素

In [14]:
c = np.array([[1, 2], [3, 4], [5, 6]])
for idx, v in np.ndenumerate(c):
    print(idx, v)
#迭代每个元素，并输出每个元素的位置

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4
(2, 0) 5
(2, 1) 6


# 三、数组操作

## 1.数值相关的数组操作

求和方法：sum；且可以通过axis指定按照哪个维度求和

In [15]:
d = np.array([[1, 2, 3], [4, 5, 6]])
d.sum(axis=0)  #按照第一维度求和

array([5, 7, 9])

In [20]:
print(np.sum(d, axis=-1))
np.sum(d, axis=1)  #维度指定规则和索引十分类似，所以可以用负数

[ 6 15]


array([ 6, 15])

求乘积使用prod函数

In [22]:
d.prod(axis=-2)

array([ 4, 10, 18])

最值以及最值对应的位置

In [25]:
print(d.argmax())  #返回索引的位置，是把数组看成一维的时候的索引
d.max()

5


6

In [26]:
print(d.argmin(axis=0))
d.min(axis=0)

[0 0 0]


array([1, 2, 3])

求平均值

In [28]:
d.mean()

3.5

In [30]:
np.average(d, axis=0, weights=[1, 2])  #average函数可以指定求平均的时候的权重

array([3., 4., 5.])

求方差标准差

In [31]:
d.std(axis=1)

array([0.81649658, 0.81649658])

In [32]:
d.var(axis=1)

array([0.66666667, 0.66666667])

数据截断：clip方法;设定最小值和最大值限制；当数组中元素小于最小值时，就会变为最小值，当大于最大值时，将会变成最大值；相当于金融衍生品中的collar

In [33]:
d.clip(6, 8)

array([[6, 6, 6],
       [6, 6, 6]])

In [43]:
a = np.arange(10)
np.clip(a, [3, 4, 1, 1, 1, 4, 4, 4, 4, 4], 8)#甚至还可以每个元素精确设定限制

array([3, 4, 2, 3, 4, 5, 6, 7, 8, 8])

极差：ptp方法

In [39]:
d.ptp()

5

近似值：round函数

In [48]:
e = np.array([1.35, 2.45, 3.55])
e.round(1)  #numpy中对于5的近似方法是，近似到与之最近的偶数；所以2.35保留一位就会近似成2.4

array([1.4, 2.4, 3.6])

In [49]:
e.all()  #所有元素都为真的时候才会返回true

True

In [50]:
e.any()  #有任意一个元素为真，即返回true

True

## 2.形状相关的数组操作

In [17]:
a = np.array([1, 2, 3, 4, 5, 6 ,7, 8])
a.shape = (2, 4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
np.reshape(a, (4,-1))  #如果有负数指定，那么py会根据另一个维度自行设定
##同时reshape不改变原始数组形状，会生成一个新的数组；同时维数必须与数组元素相对应，否则会报错

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [20]:
a.resize(2, 5, refcheck=False)
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 0, 0]])

In [21]:
b = np.array([1, 2, 3, 4,  5,  6, 7, 8])
np.resize(b, (2, 5))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 1, 2]])

In [22]:
c = np.array([1, 2, 3])
np.resize(c, (2, 4))  #注意np.resize和a.resize的不同

array([[1, 2, 3, 1],
       [2, 3, 1, 2]])

数组的转置.transpose函数

In [3]:
a = np.arange(30)
a.shape = (5, 6)
a.T.shape  #转置

(6, 5)

In [7]:
a.shape = (1, 2, 3, 5)
b = a.transpose([1, 0, 3, 2]) 
b.shape#transpose函数更加强大，可以指定转置的顺序

(2, 1, 5, 3)

In [8]:
b[0, 0, 0, 0] = 100

In [9]:
a  #可以看到transpose由于是对原来数组的引用，所以修改b的元素也会对a造成影响

array([[[[100,   1,   2,   3,   4],
         [  5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14]],

        [[ 15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29]]]])

数组降维.flat、flatten函数

In [10]:
a = np.arange(6)
a.shape = (2, 3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
b = a.flat
b[0]

0

In [14]:
b[0] = 100
a  #由于是对a 的引用，所以修改b元素会对a元素造成影响

array([[100,   1,   2],
       [  3,   4,   5]])

In [15]:
c = a.flatten()
c[1] = 200
a  #flatten方法与flat作用相同，但是是对a数组的复制，所以对a不会造成影响

array([[100,   1,   2],
       [  3,   4,   5]])

## 3.数组的拼接操作:注意这里输入需要拼接的数组时，一定要写成元组形式

concatenate函数：除了指定的拼接维度外，其他维度必须完全相同

In [18]:
a = np.arange(6)
a.shape = (2, 3)
b = np.arange(10, 16)
b.shape = (2, 3)
x = np.concatenate((a, b), axis=0)
x  #沿着行进行拼接，这里由于两个数组形状完全相同，也可以沿着列进行拼接

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [19]:
c = np.array([1, 2, 3])
np.concatenate((x, c))   #但是concatenate函数有个缺点，拼接的数组维数必须完全相同

ValueError: all the input arrays must have same number of dimensions

atleast_xd函数：最多增加到3维，会在不存在的维度添加1

In [25]:
##对于上面没法实现的合并，可以先通过这个函数调整维度，之后再进行连接操作
#1.将a, b两个二维数组合成一个三维数组
np.concatenate(np.atleast_3d(a, b), axis=2).shape

(2, 3, 2)

In [29]:
#2.把c升维成为二维数组，之后将a和c连接
np.concatenate(np.atleast_2d(a, c), axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [1, 2, 3]])

newaxis也可以增加维度，同时更加自由

In [30]:
c.shape

(3,)

In [35]:
c[ : ,np.newaxis].shape

(3, 1)

In [37]:
c[np.newaxis, : ,np.newaxis].shape  #在任意位置添加维度

(1, 3, 1)

vstack、hstack、dstack函数

In [40]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [42]:
np.hstack((a, b))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [43]:
np.dstack((a, b))

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]]])

In [44]:
##操作可以与concatenate函数相对应；同时操作相对简单，不需要对维度进行调整

## 4.四则运算、点乘和矩阵类型

In [5]:
a = np.array([[1, 2], [3, 4], [5, 6]])
np.dot(a.T, a)  #点乘

array([[35, 44],
       [44, 56]])

In [13]:
b = np.array([1, 1])
np.dot(a, b)  #维度需要匹配，否则就会出错

array([ 3,  7, 11])

In [14]:
##两个一维数组相乘就会变成一个标量
np.dot(b, b)

2

In [15]:
a = np.arange(6)
a < 3  #返回一个布尔型的数组

array([ True,  True,  True, False, False, False])

In [16]:
a == a

array([ True,  True,  True,  True,  True,  True])

In [17]:
np.all(a == a)  #返回一个结果而不是一个数组

True

In [19]:
b = np.array([np.inf, -np.inf, np.nan])
np.isnan(b)  #判断是否为nan

array([False, False,  True])

In [20]:
np.isinf(b)

array([ True,  True, False])

In [21]:
np.allclose(a, a)  #使用allclose函数来判断两个浮点数组是否相等；因为简单的使用==比较可能会有精度问题

True

# 四、广播机制

In [22]:
a = np.array([1, 2, 3, 4]).reshape(4, 1)
b = np.array([1, 2, 3])
a + b

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

规则如下：1.两个数组的形状完全一致；2.两个数组的维度个数一样，对于每个维度，两者大小相同或者其中一个为1；3.维度不同时，在低维度数组中增加大小为1的维度后与较大数组相同

# 五、数组索引

## 1.基础索引

基础索引的意思是，索引使用的是整数或者一个切片对象（slice）

In [2]:
a = np.arange(80).reshape((8, 10))

In [5]:
a[1:9:2, 0]

array([10, 30, 50, 70])

In [6]:
a[0:1,]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
a[0:1, np.newaxis, 0:2]

array([[[0, 1]]])

In [11]:
b = np.resize(a, (2, 3, 4, 5))
b[..., 1].shape

(2, 3, 4)

In [19]:
b[0, ...,1]  ##  可以使用...来省略其中的一些维度，np会根据具体的索引值对缺少的维度自动补全

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56]])

基础索引返回的是一个原来数组的引用所以可以通过索引来修改原数组的值

In [20]:
##同时也可以利用广播机制，对不止一个元素进行修改
a[1] = 0
a[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## 2.高级索引（花式索引）

花式索引是使用非元组的序列；或者布尔型的数组；

而且高级索引返回的结果始终是原数组的赋值而不是引用

### 1.整型数组索引

In [22]:
a = np.arange(80).reshape(8,10)
a[[0, 1, 2], [1, 2, 3]]

array([ 1, 12, 23])

In [23]:
rows = np.array([0, 0, 3, 3]).reshape(2, 2)
cols = np.array([0, 2, 0, 2]).reshape(2, 2)
a[rows, cols]  #索引数组是什么样子的，返回的结果就是什么形状的

array([[ 0,  2],
       [30, 32]])

In [26]:
##注意上面的数组两行是重复的，花式索引支持广播机制，所以可以利用广播进行处理
row_s = np.array([0, 3])
col_s = np.array([0, 2])
row_s.shape = (2, 1)
a[row_s, col_s]

array([[ 0,  2],
       [30, 32]])

In [4]:
a = np.arange(12).reshape(2, 3, 2)
a[[0,1], ..., [0, 1]]  #当索引中的高级索引不相邻时，高级索引对应的维度将被放在索引结果的最前面，之后是基础索引的维度
##所以这里的维度是（1，2，3）

array([[ 0,  2,  4],
       [ 7,  9, 11]])

### 2.布尔数组索引

In [5]:
a = np.array([1, 2, 3, 4, 5, 6])
a % 3 == 0

array([False, False,  True, False, False,  True])

In [6]:
a[a%3==0]

array([3, 6])

In [8]:
a[5<7]  #把位置为True的数据返回

array([[1, 2, 3, 4, 5, 6]])

# 七、随机数组

In [9]:
np.random.rand(2, 3)  #0-1均匀分布随机数

array([[0.91151384, 0.61992363, 0.33344558],
       [0.58816125, 0.41254921, 0.45200828]])

In [10]:
np.random.randn(2, 3)  #标准正态分布

array([[ 1.17342483,  0.14678903,  0.32258882],
       [-0.8197342 , -0.6288714 , -0.53453517]])

In [11]:
np.random.choice(range(5), (2, 3), replace=True)  #由放回的抽样

array([[4, 1, 4],
       [1, 3, 4]])

# 八、结构数组

当想要保存数据类型不同的数据进入数组时，同时避免非字符数据被转化为字符数据，np提供了结构数组

结构数组类似于C语言中的结构体，和对象也比较类似；结构数组通过基本类型的组合生成一种新的类型

In [29]:
person = np.dtype([("name", "S10"), ("age", "int32"), ("weight", "float64")])  #定义了三个属性
a = np.array([("Amy", 32, 69), ("Melody", 32, 99), ("Isebella", 40, 69)], dtype=person)  #每个结构（对象）都要用元组表示，否则会报错

In [30]:
a.shape  #是一个一维数组

(3,)

In [31]:
a[0]["weight"]

69.0

In [32]:
a.itemsize  # 10 + 4 + 8 = 22

22

In [45]:
b = np.array([1, 2, 3, 4])
t = np.dtype([("aaa", "float32"), ("bbb", "float32")])
c = b.view(t)
c  #这也是改变成为结构体的一种方法；但是数组的元素个数必须和属性数能够整除（也就是说可以匹配）

array([(1.e-45, 3.e-45), (4.e-45, 6.e-45)],
      dtype=[('aaa', '<f4'), ('bbb', '<f4')])